<a href="https://colab.research.google.com/github/oseiakotokwarteng-R-Insights/causal-inference-portfolio/blob/main/organ_donation_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello from R")

[1] "Hello from R"

In [2]:
install.packages("causaldata")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [3]:
install.packages("tidyverse")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [4]:
library(causaldata)
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:
data("organ_donations")

In [7]:
nrow(organ_donations)

[1] 162

In [8]:
length(unique(organ_donations$State))

[1] 27

In [9]:
unique(organ_donations$Quarter)

[1] "Q42010" "Q12011" "Q22011" "Q32011" "Q42011" "Q12012"

In [10]:
summary(organ_donations$Rate)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 0.1229  0.3346  0.4397  0.4450  0.5645  0.7900

In [13]:
organ_donations %>%
  filter(State == "California") %>%
  summarize(min = min(Rate), max = max(Rate), mean = mean(Rate), median = median(Rate))

  min    max    mean      median
1 0.2607 0.2743 0.2670667 0.26535

In [12]:
unique(organ_donations$State)

 [1] "Alaska"               "Arizona"              "California"
 [4] "Colorado"             "Connecticut"          "District of Columbia"
 [7] "Florida"              "Hawaii"               "Louisiana"
[10] "Maryland"             "Michigan"             "Minnesota"
[13] "Missouri"             "Montana"              "Nebraska"
[16] "New Hampshire"        "New Jersey"           "New York"
[19] "North Carolina"       "Ohio"                 "Pennsylvania"
[22] "South Carolina"       "Tennessee"            "Virginia"
[25] "Washington"           "Wisconsin"            "Wyoming"

In [14]:
organ_donations %>%
  filter(State %in% c("Arizona", "New York", "Ohio")) %>%
  arrange(State, Quarter_Num)

   State    Quarter Rate   Quarter_Num
1  Arizona  Q42010  0.2634 1
2  Arizona  Q12011  0.2092 2
3  Arizona  Q22011  0.2261 3
4  Arizona  Q32011  0.2503 4
5  Arizona  Q42011  0.2351 5
6  Arizona  Q12012  0.2587 6
7  New York Q42010  0.1249 1
8  New York Q12011  0.1267 2
9  New York Q22011  0.1314 3
10 New York Q32011  0.1451 4
11 New York Q42011  0.1277 5
12 New York Q12012  0.1229 6
13 Ohio     Q42010  0.5545 1
14 Ohio     Q12011  0.5593 2
15 Ohio     Q22011  0.5701 3
16 Ohio     Q32011  0.5701 4
17 Ohio     Q42011  0.5751 5
18 Ohio     Q12012  0.5645 6

In [15]:
organ_donations %>%
  filter(State %in% c("Arizona", "New York", "Ohio", "California")) %>%
  arrange(State, Quarter_Num)

   State      Quarter Rate   Quarter_Num
1  Arizona    Q42010  0.2634 1
2  Arizona    Q12011  0.2092 2
3  Arizona    Q22011  0.2261 3
4  Arizona    Q32011  0.2503 4
5  Arizona    Q42011  0.2351 5
6  Arizona    Q12012  0.2587 6
7  California Q42010  0.2666 1
8  California Q12011  0.2731 2
9  California Q22011  0.2743 3
10 California Q32011  0.2636 4
11 California Q42011  0.2607 5
12 California Q12012  0.2641 6
13 New York   Q42010  0.1249 1
14 New York   Q12011  0.1267 2
15 New York   Q22011  0.1314 3
16 New York   Q32011  0.1451 4
17 New York   Q42011  0.1277 5
18 New York   Q12012  0.1229 6
19 Ohio       Q42010  0.5545 1
20 Ohio       Q12011  0.5593 2
21 Ohio       Q22011  0.5701 3
22 Ohio       Q32011  0.5701 4
23 Ohio       Q42011  0.5751 5
24 Ohio       Q12012  0.5645 6

In [16]:
organ_donations %>%
  arrange(State, Quarter_Num)

    State       Quarter Rate   Quarter_Num
1   Alaska      Q42010  0.7500 1
2   Alaska      Q12011  0.7700 2
3   Alaska      Q22011  0.7700 3
4   Alaska      Q32011  0.7800 4
5   Alaska      Q42011  0.7800 5
6   Alaska      Q12012  0.7900 6
7   Arizona     Q42010  0.2634 1
8   Arizona     Q12011  0.2092 2
9   Arizona     Q22011  0.2261 3
10  Arizona     Q32011  0.2503 4
11  Arizona     Q42011  0.2351 5
12  Arizona     Q12012  0.2587 6
13  California  Q42010  0.2666 1
14  California  Q12011  0.2731 2
15  California  Q22011  0.2743 3
16  California  Q32011  0.2636 4
17  California  Q42011  0.2607 5
18  California  Q12012  0.2641 6
19  Colorado    Q42010  0.6653 1
20  Colorado    Q12011  0.6674 2
21  Colorado    Q22011  0.6736 3
22  Colorado    Q32011  0.6715 4
23  Colorado    Q42011  0.6699 5
24  Colorado    Q12012  0.6594 6
25  Connecticut Q42010  0.3905 1
26  Connecticut Q12011  0.3853 2
27  Connecticut Q22011  0.3952 3
28  Connecticut Q32011  0.4031 4
29  Connecticut Q42011  0.3864 5
30  Connecticut Q12012  0.3984 6
⋮   ⋮           ⋮       ⋮      ⋮
133 Tennessee   Q42010  0.3268 1
134 Tennessee   Q12011  0.3249 2
135 Tennessee   Q22011  0.3382 3
136 Tennessee   Q32011  0.3428 4
137 Tennessee   Q42011  0.3385 5
138 Tennessee   Q12012  0.3400 6
139 Virginia    Q42010  0.2645 1
140 Virginia    Q12011  0.3623 2
141 Virginia    Q22011  0.3455 3
142 Virginia    Q32011  0.3590 4
143 Virginia    Q42011  0.3443 5
144 Virginia    Q12012  0.3701 6
145 Washington  Q42010  0.5811 1
146 Washington  Q12011  0.5893 2
147 Washington  Q22011  0.5882 3
148 Washington  Q32011  0.5846 4
149 Washington  Q42011  0.5842 5
150 Washington  Q12012  0.5947 6
151 Wisconsin   Q42010  0.5735 1
152 Wisconsin   Q12011  0.5710 2
153 Wisconsin   Q22011  0.5720 3
154 Wisconsin   Q32011  0.5688 4
155 Wisconsin   Q42011  0.5660 5
156 Wisconsin   Q12012  0.5814 6
157 Wyoming     Q42010  0.5931 1
158 Wyoming     Q12011  0.5946 2
159 Wyoming     Q22011  0.5937 3
160 Wyoming     Q32011  0.5911 4
161 Wyoming     Q42011  0.5854 5
162 Wyoming     Q12012  0.5881 6

In [23]:
organ_donations %>%
  filter(Quarter_Num %in% c(3,4)) %>%
  select(State, Quarter_Num, Rate) %>%
  pivot_wider(names_from = Quarter_Num, values_from = Rate, names_prefix = "Q") %>%
  mutate(change = Q4 - Q3) %>%
  arrange(change)

   State                Q3     Q4     change
1  New Hampshire        0.5643 0.5334 -0.0309
2  California           0.2743 0.2636 -0.0107
3  Maryland             0.4679 0.4590 -0.0089
4  Washington           0.5882 0.5846 -0.0036
5  Wisconsin            0.5720 0.5688 -0.0032
6  Wyoming              0.5937 0.5911 -0.0026
7  Colorado             0.6736 0.6715 -0.0021
8  Ohio                 0.5701 0.5701  0.0000
9  Pennsylvania         0.4553 0.4559  0.0006
10 North Carolina       0.5320 0.5340  0.0020
11 Hawaii               0.4271 0.4294  0.0023
12 Missouri             0.4063 0.4089  0.0026
13 Minnesota            0.5202 0.5246  0.0044
14 Nebraska             0.4360 0.4405  0.0045
15 Tennessee            0.3382 0.3428  0.0046
16 New Jersey           0.3039 0.3109  0.0070
17 Connecticut          0.3952 0.4031  0.0079
18 South Carolina       0.2556 0.2641  0.0085
19 Alaska               0.7700 0.7800  0.0100
20 Montana              0.6578 0.6683  0.0105
21 Virginia             0.3455 0.3590  0.0135
22 New York             0.1314 0.1451  0.0137
23 Florida              0.3947 0.4181  0.0234
24 Arizona              0.2261 0.2503  0.0242
25 Louisiana            0.5619 0.5949  0.0330
26 Michigan             0.1923 0.2461  0.0538
27 District of Columbia 0.2951 0.4024  0.1073

In [24]:
organ_donations %>%
  mutate(period = ifelse(Quarter_Num <= 3, "pre", "post")) %>%
  group_by(State, period) %>%
  summarize(avg_rate = mean(Rate), .groups = "drop") %>%
  pivot_wider(names_from = period, values_from = avg_rate) %>%
  mutate (change = post-pre) %>%
  arrange(change)

   State                post      pre       change
1  New Hampshire        0.5278333 0.5604333 -3.260000e-02
2  South Carolina       0.2629000 0.2752000 -1.230000e-02
3  California           0.2628000 0.2713333 -8.533333e-03
4  Wyoming              0.5882000 0.5938000 -5.600000e-03
5  Colorado             0.6669333 0.6687667 -1.833333e-03
6  Wisconsin            0.5720667 0.5721667 -1.000000e-04
7  North Carolina       0.5250000 0.5249667  3.333333e-05
8  Pennsylvania         0.4545667 0.4540000  5.666667e-04
9  Washington           0.5878333 0.5862000  1.633333e-03
10 Nebraska             0.4437667 0.4412667  2.500000e-03
11 New York             0.1319000 0.1276667  4.233333e-03
12 Hawaii               0.4236333 0.4182000  5.433333e-03
13 Connecticut          0.3959667 0.3903333  5.633333e-03
14 Minnesota            0.5308000 0.5244333  6.366667e-03
15 Maryland             0.4700000 0.4614333  8.566667e-03
16 Ohio                 0.5699000 0.5613000  8.600000e-03
17 Missouri             0.4122000 0.4025000  9.700000e-03
18 Tennessee            0.3404333 0.3299667  1.046667e-02
19 New Jersey           0.3190000 0.3061667  1.283333e-02
20 Arizona              0.2480333 0.2329000  1.513333e-02
21 Montana              0.6626667 0.6471000  1.556667e-02
22 Louisiana            0.5648333 0.5483667  1.646667e-02
23 Alaska               0.7833333 0.7633333  2.000000e-02
24 Florida              0.4096000 0.3831667  2.643333e-02
25 Virginia             0.3578000 0.3241000  3.370000e-02
26 District of Columbia 0.3820333 0.3045333  7.750000e-02
27 Michigan             0.2990333 0.1659000  1.331333e-01

In [25]:
did_table <- organ_donations %>%
  mutate(period = ifelse(Quarter_Num <= 3, "pre", "post")) %>%
  group_by(State, period) %>%
  summarize(avg_rate = mean(Rate), .groups = "drop") %>%
  pivot_wider(names_from = period, values_from = avg_rate) %>%
  mutate (change = post-pre)

In [26]:
ca_change <- did_table %>%
  filter(State == "California") %>%
  pull(change)

In [27]:
comparison_change <- did_table %>%
  filter(State != "California") %>%
  summarize(avg_change = mean(change)) %>%
  pull(avg_change)

In [28]:
did_estimate <- ca_change - comparison_change

In [29]:
ca_change
comparison_change
did_estimate

[1] -0.008533333

[1] 0.01392564

[1] -0.02245897